version: '3.4'

services:
  myfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - storage:/storage
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  mybackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5196:80"

volumes:
  storage:

  #mybackend2:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "80"

